<a href="https://colab.research.google.com/github/selenkaptanoglu/Measurement_Problems/blob/main/Measurement_Problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import math
import scipy.stats as st
from sklearn.preprocessing import MinMaxScaler

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
pd.set_option('display.width',500)
pd.set_option('display.expand_frame_repr',False)
pd.set_option('display.float_format',lambda x: '%.3f' % x)

In [8]:
df=pd.read_csv('/content/course_reviews.csv')
df.head()

   Rating            Timestamp             Enrolled  Progress  Questions Asked  Questions Answered
0   5.000  2021-02-05 07:45:55  2021-01-25 15:12:08     5.000            0.000               0.000
1   5.000  2021-02-04 21:05:32  2021-02-04 20:43:40     1.000            0.000               0.000
2   4.500  2021-02-04 20:34:03  2019-07-04 23:23:27     1.000            0.000               0.000
3   5.000  2021-02-04 16:56:28  2021-02-04 14:41:29    10.000            0.000               0.000
4   4.000  2021-02-04 15:00:24  2020-10-13 03:10:07    10.000            0.000               0.000

In [9]:
#degerlendirme
df.shape

(4323, 6)

In [10]:
#rating dagılımı
df['Rating'].value_counts()

Rating
5.000    3267
4.500     475
4.000     383
3.500      96
3.000      62
1.000      15
2.000      12
2.500      11
1.500       2
Name: count, dtype: int64

In [11]:
df['Questions Asked'].value_counts()

Questions Asked
0.000     3867
1.000      276
2.000       80
3.000       43
4.000       15
5.000       13
6.000        9
8.000        5
9.000        3
14.000       2
11.000       2
7.000        2
15.000       2
10.000       2
22.000       1
12.000       1
Name: count, dtype: int64

In [12]:
df.groupby('Questions Asked').agg({'Questions Asked':'count',
                                   'Rating':'mean'})

                 Questions Asked  Rating
Questions Asked
0.000                       3867   4.765
1.000                        276   4.741
2.000                         80   4.806
3.000                         43   4.744
4.000                         15   4.833
5.000                         13   4.654
6.000                          9   5.000
7.000                          2   4.750
8.000                          5   4.900
9.000                          3   5.000
10.000                         2   5.000
11.000                         2   5.000
12.000                         1   5.000
14.000                         2   4.500
15.000                         2   3.000
22.000                         1   5.000

In [13]:
# Product rating average
df['Rating'].mean()

np.float64(4.764284061993986)

Time-Based Weighted Average

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4323 entries, 0 to 4322
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rating              4323 non-null   float64
 1   Timestamp           4323 non-null   object
 2   Enrolled            4323 non-null   object
 3   Progress            4323 non-null   float64
 4   Questions Asked     4323 non-null   float64
 5   Questions Answered  4323 non-null   float64
dtypes: float64(4), object(2)
memory usage: 202.8+ KB

In [16]:
df['Timestamp']=pd.to_datetime(df['Timestamp'])

In [17]:
current_date=pd.to_datetime('2021-02-10 0:0:0')

In [18]:
# dt.days gün cinsinden ifade etme bicimi
df['days']=(current_date-df['Timestamp']).dt.days

In [19]:
# 30 gün ve 30 dan az gün sayısına ulaşma
df[df['days']<=30].count()

Rating                194
Timestamp             194
Enrolled              194
Progress              194
Questions Asked       194
Questions Answered    194
days                  194
dtype: int64

In [20]:
df.loc[df['days']<=30,'Rating'].mean()

np.float64(4.775773195876289)

In [21]:
df.loc[(df['days']>30)&(df['days']<=90),'Rating'].mean()

np.float64(4.763833992094861)

In [22]:
df.loc[(df['days']>90)&(df['days']<=180),'Rating'].mean()

np.float64(4.752503576537912)

In [23]:
df.loc[(df['days']>180),'Rating'].mean()

np.float64(4.76641586867305)

In [24]:
# Calculation of Weighted Average of Score by time
def time_based_weighted_average(dataframe,w1=28,w2=26,w3=24,w4=22):
  return dataframe.loc[(dataframe['days']<=30),'Rating'].mean()*w1/100 + \
        dataframe.loc[(dataframe['days']>30) & (dataframe['days']<=90),'Rating'].mean() * w2/100 + \
        dataframe.loc[(dataframe['days']>90) & (dataframe['days']<=180),'Rating'].mean() * w3/100 + \
        dataframe.loc[(dataframe['days']>180),'Rating'].mean() * w4/100

time_based_weighted_average(df)

time_based_weighted_average(df,30,26,22,22)

np.float64(4.765491074653962)

**User-Based Weighted Average**

In [25]:
df.head()

   Rating           Timestamp             Enrolled  Progress  Questions Asked  Questions Answered  days
0   5.000 2021-02-05 07:45:55  2021-01-25 15:12:08     5.000            0.000               0.000     4
1   5.000 2021-02-04 21:05:32  2021-02-04 20:43:40     1.000            0.000               0.000     5
2   4.500 2021-02-04 20:34:03  2019-07-04 23:23:27     1.000            0.000               0.000     5
3   5.000 2021-02-04 16:56:28  2021-02-04 14:41:29    10.000            0.000               0.000     5
4   4.000 2021-02-04 15:00:24  2020-10-13 03:10:07    10.000            0.000               0.000     5

In [29]:
df.groupby('Progress').agg({'Rating': 'mean'})
df.head()

   Rating           Timestamp             Enrolled  Progress  Questions Asked  Questions Answered  days
0   5.000 2021-02-05 07:45:55  2021-01-25 15:12:08     5.000            0.000               0.000     4
1   5.000 2021-02-04 21:05:32  2021-02-04 20:43:40     1.000            0.000               0.000     5
2   4.500 2021-02-04 20:34:03  2019-07-04 23:23:27     1.000            0.000               0.000     5
3   5.000 2021-02-04 16:56:28  2021-02-04 14:41:29    10.000            0.000               0.000     5
4   4.000 2021-02-04 15:00:24  2020-10-13 03:10:07    10.000            0.000               0.000     5

In [27]:
def user_based_weighted_average(dataframe,w1=28,w2=26,w3=24,w4=22):
  return dataframe.loc[(dataframe['Progress']<=10),'Rating'].mean()*w1/100 + \
        dataframe.loc[(dataframe['Progress']>10) & (dataframe['Progress']<=45),'Rating'].mean() * w2/100 + \
        dataframe.loc[(dataframe['Progress']>45) & (dataframe['Progress']<=75),'Rating'].mean() * w3/100 + \
        dataframe.loc[(dataframe['Progress']>75),'Rating'].mean() * w4/100

user_based_weighted_average(df)

np.float64(4.790449166631202)

**Weighted Rating**

In [28]:
def course_weighted_rating(dataframe,time_w=50,user_w=50):
  return time_based_weighted_average(dataframe) * time_w/100 + user_based_weighted_average(dataframe)*user_w/100

course_weighted_rating(df)

np.float64(4.777737424449198)